import { Button } from "@mui/material";
export const data = [
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "1",
    name: "John Ofori",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "2",
    name: "Julius Caeser",
    department: "Physics",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "3",
    name: "Maxwell Adams",
    department: "Chemistry",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "4",
    name: "Dr. Wilberforce",
    department: "Computer Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "5",
    name: "Ablamagu Stellaton",
    department: "Earth Science",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
  {
    id: "6",
    name: "Charles Dickens",
    department: "Statistics & Actu Sci",
    status: "Processing",
    view: <Button children="View" variant="outlined" />,
    edit: <Button children="Edit" color="warning" variant="outlined" />,
    delete: <Button children="Delete" color="error" variant="outlined" />,
  },
];
